
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: web-test
  name: nginx-service-monitor
  namespace: web1
spec:
  endpoints:
  - interval: 10s
    port: nginx-api
  selector:
    matchLabels:
      app: web-test
  namespaceSelector:
    matchNames:
    - monitoring

