apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: web3
  labels:
    app: prometheus
spec:
  type: ClusterIP
  selector:
    app: prometheus
  ports:
  - name: prometheus
    port: 9090
    protocol: TCP
