
  name: web-test

  replicas: 3 

  image: tardocker/web-test:v2
  # repository: tardocker/web-test
  #tag: v2
  resourceslimits:
    cpu: "1"
    memory: "512Mi"
  resourserequests:
    cpu: "0.5"
    memory: "256Mi"
  ports:
    containerPort: 8000
    port: 8000
  httpGet:
    port: 8000


          
  service:  
    port: 8000
    targetPort: 8000
    type: LoadBalancer

