apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: web-test
    app.kubernetes.io/component: metrics
    app.kubernetes.io/instance: kube-prometheus
    app.kubernetes.io/name: web-test
    jobLabel: node-exporter

  name: nginx-service-monitor
  
spec:
  endpoints:
  - interval: 10s
    port: nginx-api
  selector:
    matchLabels:
      
      app.kubernetes.io/instance: kube-prometheus
      app.kubernetes.io/name: prometheus-node-exporter
      app: web-test
  namespaceSelector:
    matchNames:
    - web1

