apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9113'
  labels:
    app: web-test
  name: web-test-site
spec:
  selector:
    app: web-test
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP

