apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image }}
        resources:
          limits:
            cpu: {{ .Values.resourceslimits.cpu }}
            memory: {{ .Values.resourceslimits.memory }}
          requests:
            cpu: {{ .Values.resourserequests.cpu }}
            memory: {{ .Values.resourserequests.memory }}
        ports:
        - containerPort: {{ .Values.ports.containerPort }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.httpGet.port }}
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.httpGet.port }}
          initialDelaySeconds: 60
          periodSeconds: 10

